[powerplant]
motors = ["front left propeller", "front right propeller", "rear left propeller", "rear right propeller"]
motor_cap = inf
reversed = []
bidirectional = false
uses_propellers = true

[sensors]
accel = "accelerometer"
imu = "inertial unit"
gyro = "gyro"
gps = "gps"

[camera]
name = "camera"
mode = "color"
fps = 30
host = "0.0.0.0"
port = 5588


[rangefinder]
name = "range-finder"
fps = 30
host = "0.0.0.0"
port = 5599

[sitl]
instance = 0
sitl_address = "127.0.0.1"
